#!/bin/bash
#./build main functions
rm $1.o
rm $1.lst
rm $1
nasm -g -f elf32 $1.asm -l $1.lst
nasm -g -f elf32 $2.asm -l $2.lst
ld -melf_i386 -o $1.o $2.o


#hard-codeed build for both functions and main
#nasm -g -f -elf32 functions.asm -l functions.lst
#nasm -g -f elf32 main.asm -l main.lst
#ld -melf_i386 -o main main.o functions.o

#nasm -g -f elf32 -F dwarf $*2.asm -l $2.lst
#ld -melf_i386 -o $1.o functions.o
